### ISSUE TITLE
error occurs on trying to play a video story

### ISSUE THREAD

**Issue by MertHaddad** [iguilhermeluis/rn-stories#8]
**TypeError: null is not an object (evaluating 'RCTVideoInstance.Constants')**

This error is located at:
    in Video (at Story.tsx:41)
    in RCTView (at View.js:34)
    in View (at Story.tsx:26)
    in Story (at StoryContainer.tsx:151)
    in RCTView (at View.js:34)
    in View (at StoryContainer.tsx:150)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at TouchableOpacity.js:224)
    in TouchableOpacity (at TouchableOpacity.js:302)
    in ForwardRef (at StoryContainer.tsx:142)
    in RCTView (at View.js:34)
    in View (at react-native-swipe-gestures/index.js:121)
    in GestureRecognizer (at StoryContainer.tsx:136)
    in StoryContainer (at react-native-stories-media/index.tsx:120)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Horizontal.js:180)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Horizontal.js:222)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Horizontal.js:215)
    in CubeNavigationHorizontal (at react-native-stories-media/index.tsx:114)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at Modal.js:220)
    in RCTView (at View.js:34)
    in View (at Modal.js:242)
    in RCTModalHostView (at Modal.js:228)
    in Modal (at react-native-stories-media/index.tsx:102)
    in RCTView (at View.js:34)
    in View (at react-native-stories-media/index.tsx:81)
    in Stories (at Home.jsx:199)
    in RCTView (at View.js:34)
    in View (at Home.jsx:198)
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at Home.jsx:197)
    in RCTView (at View.js:34)
    in View (at Home.jsx:184)
    in Home (at SceneView.tsx:126)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:119)
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:210)
    in RCTView (at View.js:34)
    in View (at Screen.tsx:63)
    in RCTView (at View.js:34)
    in View (at Background.tsx:13)
    in Background (at Screen.tsx:58)
    in Screen (at BottomTabView.tsx:130)
    in RNSScreen (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at src/index.native.tsx:147)
    in Screen (at ScreenFallback.tsx:38)
    in MaybeScreen (at BottomTabView.tsx:123)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at ScreenFallback.tsx:29)
    in MaybeScreenContainer (at BottomTabView.tsx:93)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at BottomTabView.tsx:92)
    in BottomTabView (at createBottomTabNavigator.tsx:118)
    in Unknown (at createBottomTabNavigator.tsx:117)
    in BottomTabNavigator (at App.js:64)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in ForwardRef(NavigationContainerInner) (at App.js:63)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at AnimatedSplash.js:129)
    in RCTView (at View.js:34)
    in View (at AnimatedSplash.js:123)
    in RCTView (at View.js:34)
    in View (at AnimatedSplash.js:116)
    in AnimatedSplash (at App.js:53)
    in RNCSafeAreaView (at App.js:52)
    in Unknown (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\ReactFiberErrorDialog.js:43:2 in showErrorDialog
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15257:32 in logCapturedError
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15361:20 in logError
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16597:12 in update.callback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7106:2 in callCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7127:20 in commitUpdateQueue
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15801:25 in commitLifeCycles
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18744:22 in commitLayoutEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18483:29 in commitRootImpl
at node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18317:17 in commitRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17697:12 in performSyncWorkOnRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
at node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11003:16 in dispatchAction
at node_modules\react-native-stories-media\src\StoryContainer.tsx:56:21 in nextStory
at node_modules\react-native-stories-media\src\ProgressBar.tsx:39:28 in Animated.timing.start$argument_0
at node_modules\react-native\Libraries\Animated\src\nodes\AnimatedValue.js:221:28 in animation.start$argument_2
at node_modules\react-native\Libraries\Animated\src\animations\Animation.js:57:18 in __debouncedOnEnd
at node_modules\react-native\Libraries\Animated\src\animations\TimingAnimation.js:142:6 in onUpdate
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:132:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:383:16 in callTimers
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue

**Comment by MertHaddad** [comment]
This error was happening because of the source was a video and it is fixed on changing to still image.

**Comment by danteallievi** [comment]
Same issue, any fix found?

**Comment by MertHaddad** [comment]
@danteallievi nope

**Comment by Toqeer12** [comment]
****Any Update on this
